---
title: "Unsupervised Learning Lab I (L08)"
author: "Data Science III (STAT 301-3)"
date: "April 25th, 2018"
output: html_document
---

# Overview

There are two goals for this lab. The first is to continue practicing both the implementation of a consistent and organized style-guide and implementation of `tidyverse` coding enhancements to the base R code provided in the book. The second is to practice the application of unsupervised learning techniques --- Principal Component Analysis (PCA) & Clustering.

# Datasets 

We will be utilizing the `NCI60` data (*NCI60_data.csv* & *NCI60_labs.csv*) and the `USArrests` data (*USArrests.csv*) which are all contained in the **data** subdirectory. Students are able to access the appropriate codebooks by using `?ISLR::NCI60` or `USArrests`.

# Exercises

Please complete the following exercises. The document should be neatly formatted. 

#### Load Packages

```{r, message=FALSE}
# Loading package(s)

```
<br>

#### Exercise 1
Work through the lab in Section 10.4 *Lab 1: Principal Compenent Analysis* (pages: 401 - 404) while attempting to utilize `tidyverse` techniques when possible. 

<br><br>

#### Exercise 2
Work through the lab in Section 10.5 *Lab 2: Clustering* (pages: 404 - 407) while attempting to utilize `tidyverse` techniques when possible. 

<br><br>

#### Exercise 3
Work through the lab in Section 10.5 *Lab 3: NCI60 Data Example* (pages: 407 - 413) while attempting to utilize `tidyverse` techniques when possible.

<br><br>

***

Please note that *"attempting to utilize `tidyvere` techniques when possible"* entails that students make an **honest** effort to implement these techniques. Copying, pasting, running, and submitting the code provided in the book does not constitute an **honest** effort. 

While it might feel redundant to re-create code in a slightly different format, it is an extremely useful skill to practice. It is only really redundant because base R code is supplied. The base R code provides a good starting point for us to build upon and improve it by converting it to a more flexible and organized format. Students should also consider adding their own notes and commentary to make this lab into a useful resource for the future. 